import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import SideBar from "../components/SideBar"
import ProfilePanel from "@/components/ProfilePanel"
import NotificationContextProvider from "./context/NotificationContextProvider"

import { getRequest, ServiceRoutes } from "./api/http"
import { ProjectContextProvider } from "./context/ProjectContextProvider"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Bugtracker",
  description: "Generated by Mister X",
}

let serverInit = false

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  let response = await await getRequest(
    ServiceRoutes.project + "/project_members?userId=1234"
  )
  const projects = await response.json()
  return (
    <html className="w-full h-full">
      <body className="h-full w-full flex ">
        <ProjectContextProvider projects={projects}>
          <SideBar projects={[]} />
          <div className="w-full py-7 px-4">
            <NotificationContextProvider>
              <ProfilePanel />
              {children}
            </NotificationContextProvider>
          </div>
        </ProjectContextProvider>
      </body>
    </html>
  )
}
