import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import SideBar from "../components/SideBar"
import ProfilePanel from "@/components/ProfilePanel"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Bugtracker",
  description: "Generated by Mister X",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  
  return (
    <html className="w-full h-full">
      <body className="h-full w-full flex ">
        <SideBar />
        <div className="w-full py-7 px-4">
          <ProfilePanel />
          {children}
        </div>
      </body>
    </html>
  )
}
